POST http://127.0.0.1:4000/signup
Content-Type: application/json

{
    "username": "ffdssds",
    "password": "123"
}

###

POST http://127.0.0.1:4000/login
Content-Type: application/json

{
    "username": "john",
    "password": "123"
}